### ISSUE TITLE
Incorrect type compatibility of JS data types

### ISSUE THREAD

**Issue by leushkin** [JSMonk/hegel#187] opened 2020-04-29 12:26 UTC
https://hegel.js.org/try#MYewdgzgLgBAZiEMC8NoCcUD41XQOihAFUAHUgU3QGEBDCCgCgEoAoVhERgcgAsKANgJDdmQA

I agree with a type of foo function, but when I try to apply string to this function Hegel returns an error. Hegel should consider string | number | ... also as objects with methods

**Comment by thecotne** [comment] 2020-04-29 12:32
duplicate of https://github.com/JSMonk/hegel/issues/126

**Comment by JSMonk** [comment] 2020-04-29 22:36
Thank you for your contribution ^_^. I will fix it with #126.

**Closed** 2020-05-10 00:01 UTC
Labels: bug, duplicate
